LOAD DATA
CHARACTERSET UTF8
INFILE '/tmp/workspace/kafka-python/csv/20171019/ccp-all.csv'
BADFILE	'/tmp/workspace/kafka-python/csv/20171019/ccp-all.bad'
DISCARDFILE	'/tmp/workspace/kafka-python/csv/20171019/ccp-all.dsc'
APPEND INTO TABLE TGW_CCP_DEV 
FIELDS TERMINATED BY '|'
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    NOTIFICATION_ID,
    EVENT_BEGINTIME DATE "YYYY-MM-DD HH24-MI-SS",
    MSISDN,   
    EVENT_TYPE,
    IMSI,
    SUBSCRIBER_PRICEPLANCODE,
    DEF_LANGUAGE,
    CHAIN_ID,    
    ACTIVATION_DATE DATE "YYYY-MM-DD HH24-MI-SS",
    TOPPING_ID ,
    PRICE ,
    ACCOUNT_TYPE,
    OLD_PRICEPLANCODE,
    NEW_PRICEPLANCODE,
    REQUEST_ID,
    BALANCE_TYPE,
    AMOUNT ,
    NEW_BALANCE ,
    VALIDITY,
    NEW_VALIDITY,
    SUBSCRIBER_PRICEPLAN_ID,
    MESSAGE_TYPE,
    SERVICE_ID,
    SERVICE_TYPE,
    TRANSACION_SN,
    ACCUM_COUNT ,
    ACCUM_AMOUNT ,
    CELLA,
    EFFECTIVE_DATE DATE "YYYY-MM-DD HH24-MI-SS",
    EXPIRE_DATE DATE "YYYY-MM-DD HH24-MI-SS",
    ODS_PPN_BY constant "TEST",
    ODS_PPN_TM "SYSDATE" ,
    ODS_UPD_BY constant "TEST",
    ODS_UPD_TM "SYSDATE" ,
    ODS_ACTION constant "I",
    OSB_RECEIVETIME "SYSDATE"  
)


